name: [Actions Workflow]

on: [push]

jobs:
  run-github-actions:
    runs-on: ubunto-latest
    steps:  
      - name: simple JS Action
        uses: action/hello-world-javascript-action@v1.1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"  
          
