name: Context

on:[push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo ${{ contains( 'hello', 'll' ) }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', 'lo' ) }}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', '!' ) }}dump_contexts_to_log:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
 (...)